package com.merseyside.dropletapp.providerApi

const val AUTHORIZATION_KEY = "Authorization"
const val NAME_KEY = "name"
const val PUBLIC_KEY = "public_key"
const val REGION_KEY = "region"
const val SSH_KEYS = "ssh_keys"
const val TAG_KEY = "tags"
const val IMAGE_KEY = "image"
const val SIZE_KEY = "size"
const val BACKUPS_KEY = "backups"
const val DROPLET_KEY = "droplet_id"
const val LABEL_KEY = "label"
const val SSH_KEY = "ssh_key"
const val AUTHORIZED_KEYS = "authorized_keys"
const val TYPE_KEY = "type"
const val ROOT_PASS_KEY = "root_pass"
const val SSH_KEY_ID = "ssh_key_id"
const val KEY = "key"
const val USER_DATA="user_data"